language: c

matrix:
  include:
    - os: linux
      env: NAME="script build"
      sudo: required
      dist: trusty
      services: docker
      addons:
        apt:
          packages:
            - zip 
            - curl
      script: "./.travis/build.sh"

before_script:
      - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      - curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
      - sudo apt-get update
      - sudo apt-get install -y powershell
      - chmod +x ./.travis/build.sh

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "EventMacrosBR"
      - git config --local user.email "noreply@noreply.org"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: 
    secure: MIIEpAIBAAKCAQEAmATEnuq2cY2VmZe5+kM+ckISiimJ6T4CwHktRp2IXNB9bAx88LBmCBBadA5kcfMXKIQoCZGRnD6s1IEByBHssm4Di2BHMVDwdO3iAlnjX5G3CR1Tw9sZgmLQ0k/+kIvraU+Ea6lgjcS/rCB+quZrT5qiBh5nV5M4fx09b7LkjjFw5O5nsToKMyMDOks8MtumI5dQVFUz6WCdac2XsDXccsiZe/kqlgCf3hUbYBXqurBBdn2kptiLFd3YMwrHUdMzS08FokhIJAN/FSaxS/TrwhUfIRZxMKecrqo81Lb/zJKNTMDvoB/0RmHGhEMVaOLUCt5G2I7aEi3Tt1eo6Y7M6QIDAQABAoIBAGmetnWrogMXWh+S+ZZV7ic4nOT9o2I4wXS1PK3ZegrymJHfw1b/WIS1yALmlQdO3II8AA1V5JNoQHCNCY3WVlxKb5AA3rX3BHpZZTQ4++9EsKVWiQKFUh3zRh85kScg7/kFVH3w+rLFRl7zXM6ktV5jk7somKiSEyjOSgc3hfD8erw3TU0KCcvB96q7GlDjP9SJWbniMVLcsKoTjEV58WCQ0fGb7N97CGtOm2vUwvmghqDPUdEGrinSQfEOKX1gudCD9q7rxfYivrYPYutQhKEHsF33gjn5fRtx+iYmh2XFELYdhvssFe5ZBRgLSDZ9svWoWUvhz73nUQFVlJkWwAECgYEAyhwLzxDa4fBjq1wo255RaeJlTbtQ4vQfFRdBBVlcrD4o+/TQSLfRU7D8HkpLidg6lAmfrKWAb36E2LgoDf/iv0ZROYRgHvBpPtmBdqI+vRJjkfLdvUDqK1dXawutLVYNbYp3mFJ+C0l5kT/9J6UitC+iRTCfLL3RXY0ZXMqsmOkCgYEAwI2Gqkc1ME00vMgi0jcz/5qXrhbrlUizP82piP1MFucmGyibUxRN571hGDFZcmxxHF2euiAsYhFkMtv636p2/C55GJiL36cfevrsJEhiPl/spNcw4xB/E1VIPabOiIHaCeSufS536AHZZwRV8HQNEpSXDsyhrVqHQ4Ftv7VwFAECgYBoWyjhxtMt3ECqZ1CVbV6eLI6gHzr5pJE0A6jICUcnjIT+635sPbVw4C6duUDdsO82Ju3yaBYz+4C+of/Ukq5Skw03hJlZAEtnb0lApy970rXk0yEZKh5/OH7jv8iwYwFV8SwlU1rPmyWRERg20zZjEUFZNmzJ3kzvX/6bge6ymQKBgQCz1jq05Ga34xPjUWS8Q1SsYJ1TuhJzTgAkEhhKWpBrP53mdamEEY2lZ8m8R7ML3F5UKNgrbAsn2Khlm/EWXuZcJ6dwImFZFIShXqOYS4Z+TSb+2gDNwcV9sAQVmKqC8gxLeyrAvdq9dKSww2rkde8TsHXZG6PQ/aEhmkt/Zpz0AQKBgQClSJOdJcWzrlccxFy6n9adCBqTcvUc5FgDrmsoI0nIVxMcjJJdB+vg8F1nPWkDFgJgzXNWu8gwaEhgJQJVsdsO83X21PCMIcRMreVO/Kb4c0PPvZMurPqXYUGYg2cRJyO+QSJ/+BxV0HBcWAl3b8RU5npcaMbM9sijMWeZexmZag==
  file: build.zip
  skip_cleanup: true