language: c

matrix:
  include:
    - os: linux
      env: NAME="script build"
      sudo: required
      dist: trusty
      services: docker
      addons:
        apt:
          packages:
            - zip 
            - curl
      script: "./.travis/build.sh"

before_script:
      - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      - curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
      - sudo apt-get update
      - sudo apt-get install -y powershell
      - chmod +x ./.travis/build.sh

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "EventMacrosBR"
      - git config --local user.email "noreply@noreply.org"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: 
     secure: "JlZciU0J15uRGP0BLLLpSYBCgZ+rVLLBnoXA410666pZ7ykWzvhN88fQVWfFN5Q2IlgnMpd6LbYt8QyVOzziztVgG6euKVUdCfphTLGQYshdf/4+bScm7a2PeAfQm8MDs/TR+voSB/z8AO+KunICJ8M8NY6QIaaHMK419FSiirnJD7DL1Z1rqGDjISR7aGnAAc0j9L/NSSghynlHcrOsEvStcN7wScgSkM9jU7r5vnnz3qYrqwmlnKJhxHOMqxzgjz8CdMVJZk5VnDV413O2mi7WQi6tYFl72N1TMblLV6qdPJPXG4nQitf88fBNi9RsE9S8DTV1FoJRTsswOziiUFYeEVPXNvWmZRaJARq3OWqtJliqB0Du00vP5VS3wTBvDF26/CaljXCOcyUvS1KE4dWDFjc7HncXPbO3ur+aJ+uFLXsBQF0QNFg8y7M7q0fN/err04vpRzAvQB/WNH8l83rZBirUDOy2NGtphCTAv4dTvF4k3Hjek2CgBO+jnuOYCUfpwGVLLsdNRjysGzAhpgUiuhjKd8B5Lq1650+GocfKicltSuQJCxmF2RfKBxoBV7ufBY57JMcVZelYjL7PCtiqNLmoCRGcvRDz6IWxUp7KjMNjRzxy2oWrHD35i5jK3UkqMA1+4BVeZTl2a4N0nR+nX5d8I4SYszLhXHOmG6I="
  file: build.zip
  skip_cleanup: true